- name: Activate Master node
  hosts: all
  tasks:
    - name: Initialize master
      shell: kubeadm init
      become: yes
    - name: Export2
      shell: kubectl version | base64 | tr -d '\n'
      register: output
    - name: Print
      debug: msg="kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{ output.stdout }} --kubeconfig=/etc/kubernetes/admin.conf"
    - name: Exec all
      shell: "kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{ output.stdout }}  --kubeconfig=/etc/kubernetes/admin.conf"
      become: yes
      register: output2
    - name: output
      debug:
        msg: "{{ output2.stdout }}"

